sudo: required
services:
    - docker

before_install:
    - docker build -t camilojimenezf/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true camilojimenezf/react-test npm test

after_success:
    - docker build -t camilojimenezf/multi-client ./client
    - docker build -t camilojimenezf/multi-nginx ./nginx
    - docker build -t camilojimenezf/multi-server ./server
    - docker build -t camilojimenezf/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push camilojimenezf/multi-client
    - docker push camilojimenezf/multi-nginx
    - docker push camilojimenezf/multi-server
    - docker push camilojimenezf/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-406429456611
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_acess_key: $AWS_SECRET_KEY